version: '3.8'

services:
  wasolution:
    image: meuconsig/wasolution:1.0.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - wasolution-network

networks:
  wasolution-network:
    driver: overlay  # Changed from bridge to overlay for Swarm mode
