// ...existing code...
auto stat = /* chamada da requisição */;
if (stat == c_status::OK) {
    // ...código para montar corpo da resposta de sucesso...
    return crow::response(200, /* corpo da resposta */);
} else if (stat == c_status::ERR) {
    // ...código para montar corpo da resposta de erro...
    return crow::response(500, /* corpo da resposta de erro ou mensagem */);
}
// ...existing code...